name: ResourceMadness
main: com.mtaye.ResourceMadness.RM
version: 0.1
author: mtaye
description: ResourceMadness!
commands:
 resourcemadness:
  description: Access to all ResourceMadness commands
  aliases:
      - rm