name: ResourceMadness
main: com.mtaye.ResourceMadness.RM
version: 0.1
author: M-Taye
description: Competitive team-based resource gathering
commands:
 resourcemadness:
  description: Access to ResourceMadness commands
  aliases:
      - rm